### ISSUE TITLE
Unexpected token ,

### ISSUE THREAD

**Issue by christopher5106** [mateogianolio/mlp-character-recognition#5]
Dears

I've installed the lib and when I run the main.js, I get the following error : 

$ node main.js
reading config file ...
... done

generating images ...
... done

layers:
  input: 256 neurons.
  hidden: 40 neurons.
  output: 4 neurons.
learning rate: 0.03 

training with 200000 inputs ...
progress: 0 %
progress: 10 %
progress: 20 %
progress: 30 %
progress: 40 %
progress: 50 %
progress: 60 %
progress: 70 %
progress: 80 %
progress: 90 %
... done (4 min 46 s 712 ms)

undefined:11137
F[256] = F[257];,F[257] = F[258];,F[257] += F[0] \* F[259];,F[257] += F[1] \* F[
                ^
SyntaxError: Unexpected token ,
    at Function (native)
    at Perceptron.Network.standalone (/Users/christopherbourez/apps/mlp-character-recognition/node_modules/synaptic/src/network.js:489:12)
    at /Users/christopherbourez/apps/mlp-character-recognition/main.js:195:49
    at null.<anonymous> (/Users/christopherbourez/apps/mlp-character-recognition/node_modules/pngjs/lib/png.js:84:13)
    at g (events.js:199:16)
    at emit (events.js:107:17)
    at null.<anonymous> (/Users/christopherbourez/apps/mlp-character-recognition/node_modules/pngjs/lib/png.js:52:14)
    at emit (events.js:107:17)
    at Parser._reverseFiltered (/Users/christopherbourez/apps/mlp-character-recognition/node_modules/pngjs/lib/parser.js:358:10)
    at emit (events.js:118:17)

**Comment by mateogianolio** [comment]
That's weird. Can you paste your config file?

**Comment by christopher5106** [comment]
Are you talking about config.json file ?

{
  "mnist": false,
  "text": "0123456789",
  "fonts": [
    "sans-serif",
    "serif"
  ],
  "training_set": 20000,
  "testing_set": 500,
  "image_size": 16,
  "threshold": 400,
  "network": {
    "hidden": 40,
    "output": 4,
    "learning_rate": 0.03
  }
}

**Comment by vellengs** [comment]
Same error with you.

**Comment by mateogianolio** [comment]
I just updated all dependencies' minimum versions in package.json, can you try clone the repo again and then run:

``` bash
$ npm install
$ node main.js
```

It works for me now (on OSX).

**Comment by vellengs** [comment]
Hi mateogianolio,  I updated the newest   synaptic  to  1.0.2 , that works

**Comment by mateogianolio** [comment]
Nice :) closing this
